/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dnfapp;

/**
 *
 * @author Frans
 */
public class EditKurir extends javax.swing.JFrame {

    /**
     * Creates new form EditKurir
     */
    public EditKurir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameEditField = new javax.swing.JTextField();
        UsernameEditField = new javax.swing.JTextField();
        PasswordEditField = new javax.swing.JTextField();
        KeluarButton = new javax.swing.JButton();
        BG_EditKurir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameEditField.setBackground(new java.awt.Color(62, 97, 155));
        NameEditField.setBorder(null);
        NameEditField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameEditFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NameEditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 212, 380, 30));

        UsernameEditField.setBackground(new java.awt.Color(62, 97, 155));
        UsernameEditField.setBorder(null);
        getContentPane().add(UsernameEditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 281, 380, 30));

        PasswordEditField.setBackground(new java.awt.Color(62, 97, 155));
        PasswordEditField.setBorder(null);
        getContentPane().add(PasswordEditField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 380, 30));

        KeluarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_5_minisize.png"))); // NOI18N
        KeluarButton.setBorder(null);
        KeluarButton.setContentAreaFilled(false);
        KeluarButton.setDefaultCapable(false);
        getContentPane().add(KeluarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 585, 90, 90));

        BG_EditKurir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Profile_Kurir.png"))); // NOI18N
        BG_EditKurir.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(BG_EditKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameEditFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameEditFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameEditFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditKurir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_EditKurir;
    private javax.swing.JButton KeluarButton;
    private javax.swing.JTextField NameEditField;
    private javax.swing.JTextField PasswordEditField;
    private javax.swing.JTextField UsernameEditField;
    // End of variables declaration//GEN-END:variables
}
