/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dnfapp;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;

/**
 *
 * @author Felicia Pangestu
 */
public class ListPaketKurir extends javax.swing.JFrame {

    /**
     * Creates new form ListPaketKurir
     */
    private Kurir currentKurir;
    //HashMaps to Pass.
    private HashMap<String, User> userlist = new HashMap<String, User>();
    private HashMap<String, String> usedEmail = new HashMap<String, String>();
    private HashMap<String, Package> DeliveryList = new HashMap<String, Package>();
    private HashMap<String, Kurir> ListKurir = new HashMap<String, Kurir>();
    private ArrayList<Package> ARRPackageList = new ArrayList<>();
    
    //private Generated HashMaps&ArrayList for City Index
    private HashMap<String, Kota> MapKota = new HashMap<String, Kota>();
    private ArrayList<String> listkota = new ArrayList<>();
    
    private void generateElement() {
        generate();
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < ARRPackageList.size(); i++) {
            String container = ARRPackageList.get(i).getResi() + ARRPackageList.get(i).getReceiver() + " - " + ARRPackageList.get(i).getDestination();
            listModel.addElement(container);
        }
        listPaket.setModel(listModel);
    }

    private void generate() {
        for (Map.Entry<String, Package> set : DeliveryList.entrySet()) {
            this.ARRPackageList.add(set.getValue());
        }
        System.out.println(ARRPackageList.get(0));
    }
    
     public ListPaketKurir() {
        initComponents();
        bgListPaket.requestFocus();
        generateElement();
     }
     
    public ListPaketKurir(HashMap<String, User> userlist, HashMap<String, String> usedEmail){
        initComponents();
        this.userlist=userlist;
        this.usedEmail=usedEmail;
        generateElement();
    }
    
    public ListPaketKurir(HashMap<String, User> userlist,HashMap<String, String> usedEmail, HashMap<String, Package> DeliveryList,  HashMap<String, Kurir> ListKurir, Kurir currentKurir){
        initComponents();
        this.userlist=userlist;
        this.usedEmail=usedEmail;
        this.DeliveryList=DeliveryList;
        this.ListKurir=ListKurir;
        this.currentKurir=currentKurir;
        this.setResizable(false);
        generateElement();
        bgListPaket.requestFocus();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namaPengirim = new javax.swing.JTextField();
        alamatPengirim = new javax.swing.JTextField();
        namaPenerima = new javax.swing.JTextField();
        alamatPenerima = new javax.swing.JTextField();
        btnKluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPaket = new javax.swing.JList<>();
        bgListPaket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaPengirim.setBackground(new java.awt.Color(62, 97, 155));
        namaPengirim.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        namaPengirim.setBorder(null);
        jPanel1.add(namaPengirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 270, -1));

        alamatPengirim.setBackground(new java.awt.Color(62, 97, 155));
        alamatPengirim.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        alamatPengirim.setBorder(null);
        jPanel1.add(alamatPengirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 260, -1));

        namaPenerima.setBackground(new java.awt.Color(62, 97, 155));
        namaPenerima.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        namaPenerima.setBorder(null);
        jPanel1.add(namaPenerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 270, -1));

        alamatPenerima.setBackground(new java.awt.Color(62, 97, 155));
        alamatPenerima.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        alamatPenerima.setBorder(null);
        jPanel1.add(alamatPenerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 260, -1));

        btnKluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_5_minisize.png"))); // NOI18N
        btnKluar.setBorderPainted(false);
        btnKluar.setContentAreaFilled(false);
        btnKluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKluarMouseClicked(evt);
            }
        });
        jPanel1.add(btnKluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 510, -1, -1));

        listPaket.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jScrollPane1.setViewportView(listPaket);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 400, 380));

        bgListPaket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kurir_BG_ListPaket.png"))); // NOI18N
        jPanel1.add(bgListPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKluarMouseClicked

        KurirMainMenu LM = new KurirMainMenu(userlist, usedEmail, DeliveryList, ListKurir, currentKurir);
        dispose();
        LM.setVisible(true);
        LM.pack();
        LM.setLocationRelativeTo(null);
        LM.setDefaultCloseOperation(CreateAccountPage.EXIT_ON_CLOSE);
        LM.setResizable(false);
    }//GEN-LAST:event_btnKluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPaketKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPaketKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPaketKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPaketKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPaketKurir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatPenerima;
    private javax.swing.JTextField alamatPengirim;
    private javax.swing.JLabel bgListPaket;
    private javax.swing.JButton btnKluar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listPaket;
    private javax.swing.JTextField namaPenerima;
    private javax.swing.JTextField namaPengirim;
    // End of variables declaration//GEN-END:variables
}
