/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dnfapp;

import java.util.HashMap;
import java.util.Map;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
/**
 *
 * @author Frans
 */
public class ListPengiriman extends javax.swing.JFrame {

    private HashMap<String, User> userlist = new HashMap<String, User>();
    private HashMap<String, Package> DeliveryList = new HashMap<String, Package>();
    private HashMap<String, String> usedEmail = new HashMap<String, String>();
    private HashMap<String, Kurir> ListKurir = new HashMap<String, Kurir>();
    private ArrayList<Package> ARRListPackage = new ArrayList<>();
    private Integer SelectedObj = null;
    /**
     * Creates new form ListPengiriman
     */
    public ListPengiriman() {
        initComponents();
    }
    
    public ListPengiriman(HashMap<String, User> userlist, HashMap<String, String> usedEmail, HashMap<String, Package> DeliveryList, HashMap<String, Kurir> ListKurir){
        initComponents();
        this.userlist = userlist;
        this.usedEmail = usedEmail;
        this.DeliveryList = DeliveryList;
        this.ListKurir = ListKurir;
        generateElement();
    }
    
    private void generateList(){
        for (Map.Entry<String, Package> set : DeliveryList.entrySet()) {
            this.ARRListPackage.add(set.getValue());
        }
    }
    
    private void generateElement(){
        generateList();
        if(this.ARRListPackage.size()!=0){
            DefaultListModel listModel = new DefaultListModel();
            for (int i = 0; i < ARRListPackage.size(); i++) {
                String container = ARRListPackage.get(i).getResi() + " - " + ARRListPackage.get(i).getSender()+" - " +ARRListPackage.get(i).getReceiver();
                listModel.addElement(container);
            }
            DaftarPengiriman.setModel(listModel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DaftarPengiriman = new javax.swing.JList<>();
        ExitButton = new javax.swing.JButton();
        ReceiverField = new javax.swing.JLabel();
        SenderField = new javax.swing.JLabel();
        LabelAsal = new javax.swing.JLabel();
        LabelTujuan = new javax.swing.JLabel();
        LabelBerat = new javax.swing.JLabel();
        LabelKeterangan = new javax.swing.JLabel();
        BGKeterangan = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DaftarPengiriman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DaftarPengirimanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DaftarPengiriman);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 400, 380));

        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_5_minisize.png"))); // NOI18N
        ExitButton.setBorderPainted(false);
        ExitButton.setContentAreaFilled(false);
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 75, 75));
        getContentPane().add(ReceiverField, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 260, 30));
        getContentPane().add(SenderField, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 270, 20));
        getContentPane().add(LabelAsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 260, 20));
        getContentPane().add(LabelTujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 280, 20));
        getContentPane().add(LabelBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 270, 20));

        LabelKeterangan.setFont(new java.awt.Font("Fira Sans", 3, 11)); // NOI18N
        LabelKeterangan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(LabelKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 280, 80));

        BGKeterangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG_Keterangan_Pengiriman.png"))); // NOI18N
        getContentPane().add(BGKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 340, 120));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Daftar_Pengiriman.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DaftarPengirimanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaftarPengirimanMouseClicked
        SelectedObj=DaftarPengiriman.getSelectedIndex();
        ReceiverField.setText(ARRListPackage.get(SelectedObj).getReceiver());
        SenderField.setText(ARRListPackage.get(SelectedObj).getSender());
        LabelAsal.setText(ARRListPackage.get(SelectedObj).getFrom());
        LabelTujuan.setText(ARRListPackage.get(SelectedObj).getDestination());
        LabelBerat.setText(Integer.toString(ARRListPackage.get(SelectedObj).getWeight()));
        if(ARRListPackage.get(SelectedObj) instanceof Others){
            Others tempObj = (Others) ARRListPackage.get(SelectedObj);
            String text = tempObj.getKeterangan();
            LabelKeterangan.setText(text);
        }
        else{
            String text = ARRListPackage.get(SelectedObj).getClassName();
            LabelKeterangan.setText(text);
        }
    }//GEN-LAST:event_DaftarPengirimanMouseClicked

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        AdminMenu AM = new AdminMenu(userlist, DeliveryList, ListKurir, usedEmail);
        dispose();
        AM.setVisible(true);
        AM.pack();
        AM.setResizable(false);
        AM.setLocationRelativeTo(null);
        AM.setDefaultCloseOperation(AdminMenu.EXIT_ON_CLOSE);
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPengiriman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPengiriman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPengiriman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPengiriman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPengiriman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel BGKeterangan;
    private javax.swing.JList<String> DaftarPengiriman;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel LabelAsal;
    private javax.swing.JLabel LabelBerat;
    private javax.swing.JLabel LabelKeterangan;
    private javax.swing.JLabel LabelTujuan;
    private javax.swing.JLabel ReceiverField;
    private javax.swing.JLabel SenderField;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
