/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dnfapp;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Felicia Pangestu
 */
public class ListPaketKurir extends javax.swing.JFrame {

    /**
     * Creates new form ListPaketKurir
     */
    private Kurir currentKurir;
    //HashMaps to Pass.
    private HashMap<String, User> userlist = new HashMap<String, User>();
    private HashMap<String, String> usedEmail = new HashMap<String, String>();
    private HashMap<String, Package> DeliveryList = new HashMap<String, Package>();
    private HashMap<String, Kurir> ListKurir = new HashMap<String, Kurir>();
    private ArrayList<Package> ARRPackageList = new ArrayList<>();

    //private Generated HashMaps&ArrayList for City Index
    private HashMap<String, Kota> MapKota = new HashMap<String, Kota>();
    private ArrayList<String> listkota = new ArrayList<>();

    private void generateElement() {
        generate();
        DefaultListModel listModel = new DefaultListModel();
        for (int i = 0; i < ARRPackageList.size(); i++) {
            String container = ARRPackageList.get(i).getResi() + " - " + ARRPackageList.get(i).getReceiver() + " - " + ARRPackageList.get(i).getDestination();
            listModel.addElement(container);
        }
        listPaket.setModel(listModel);
    }

    private void generate() {
        for (Map.Entry<String, Package> set : DeliveryList.entrySet()) {
            if (set.getValue().getTrack().get(set.getValue().getTrack().size() - 1).equals("Barang diterima DNF")) {
                this.ARRPackageList.add(set.getValue());
            }
        }
//        System.out.println(ARRPackageList.get(0));
    }

    public ListPaketKurir() {
        initComponents();
        bgListPaket.requestFocus();
        generateElement();
    }

    public ListPaketKurir(HashMap<String, User> userlist, HashMap<String, String> usedEmail) {
        initComponents();
        this.userlist = userlist;
        this.usedEmail = usedEmail;
        generateElement();
    }

    public ListPaketKurir(HashMap<String, User> userlist, HashMap<String, String> usedEmail, HashMap<String, Package> DeliveryList, HashMap<String, Kurir> ListKurir, Kurir currentKurir) {
        initComponents();
        this.userlist = userlist;
        this.usedEmail = usedEmail;
        this.DeliveryList = DeliveryList;
        this.ListKurir = ListKurir;
        this.currentKurir = currentKurir;
        this.setResizable(false);
        generateElement();
        bgListPaket.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namaPengirim = new javax.swing.JTextField();
        alamatPengirim = new javax.swing.JTextField();
        namaPenerima = new javax.swing.JTextField();
        alamatPenerima = new javax.swing.JTextField();
        btnKluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPaket = new javax.swing.JList<>();
        pickupButton = new javax.swing.JButton();
        bgListPaket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaPengirim.setBackground(new java.awt.Color(62, 97, 155));
        namaPengirim.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        namaPengirim.setForeground(new java.awt.Color(255, 255, 255));
        namaPengirim.setBorder(null);
        namaPengirim.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        namaPengirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPengirimActionPerformed(evt);
            }
        });
        jPanel1.add(namaPengirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 270, -1));

        alamatPengirim.setBackground(new java.awt.Color(62, 97, 155));
        alamatPengirim.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        alamatPengirim.setForeground(new java.awt.Color(255, 255, 255));
        alamatPengirim.setBorder(null);
        alamatPengirim.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        alamatPengirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatPengirimActionPerformed(evt);
            }
        });
        jPanel1.add(alamatPengirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 260, -1));

        namaPenerima.setBackground(new java.awt.Color(62, 97, 155));
        namaPenerima.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        namaPenerima.setForeground(new java.awt.Color(255, 255, 255));
        namaPenerima.setBorder(null);
        namaPenerima.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        namaPenerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaPenerimaActionPerformed(evt);
            }
        });
        jPanel1.add(namaPenerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 270, -1));

        alamatPenerima.setBackground(new java.awt.Color(62, 97, 155));
        alamatPenerima.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        alamatPenerima.setForeground(new java.awt.Color(255, 255, 255));
        alamatPenerima.setBorder(null);
        alamatPenerima.setCaretColor(new java.awt.Color(255, 255, 255));
        alamatPenerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatPenerimaActionPerformed(evt);
            }
        });
        jPanel1.add(alamatPenerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 431, 260, 20));

        btnKluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Icon_5_minisize.png"))); // NOI18N
        btnKluar.setBorderPainted(false);
        btnKluar.setContentAreaFilled(false);
        btnKluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKluarMouseClicked(evt);
            }
        });
        btnKluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 510, -1, -1));

        listPaket.setBackground(new java.awt.Color(4, 37, 107));
        listPaket.setBorder(null);
        listPaket.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        listPaket.setForeground(new java.awt.Color(255, 255, 255));
        listPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPaketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listPaket);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 400, 380));

        pickupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kurir_Button_AmbilPaket.png"))); // NOI18N
        pickupButton.setBorderPainted(false);
        pickupButton.setContentAreaFilled(false);
        pickupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickupButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pickupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, -1));

        bgListPaket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kurir_BG_ListPaket.png"))); // NOI18N
        jPanel1.add(bgListPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKluarMouseClicked

        KurirMainMenu LM = new KurirMainMenu(userlist, usedEmail, DeliveryList, ListKurir, currentKurir);
        dispose();
        LM.setVisible(true);
        LM.pack();
        LM.setLocationRelativeTo(null);
        LM.setDefaultCloseOperation(CreateAccountPage.EXIT_ON_CLOSE);
        LM.setResizable(false);
    }//GEN-LAST:event_btnKluarMouseClicked

    private void listPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPaketMouseClicked
        // TODO add your handling code here:
        int SelectedObj = listPaket.getSelectedIndex();
        namaPenerima.setText(ARRPackageList.get(SelectedObj).getReceiver());
        namaPengirim.setText(ARRPackageList.get(SelectedObj).getSender());
        alamatPengirim.setText(ARRPackageList.get(SelectedObj).getFrom());
        alamatPenerima.setText(ARRPackageList.get(SelectedObj).getDestination());

    }//GEN-LAST:event_listPaketMouseClicked

    private void namaPengirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPengirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPengirimActionPerformed

    private void alamatPengirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatPengirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatPengirimActionPerformed

    private void namaPenerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaPenerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaPenerimaActionPerformed

    private void alamatPenerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatPenerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatPenerimaActionPerformed

    private void pickupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickupButtonActionPerformed
        // TODO add your handling code here:
        int SelectedObj = listPaket.getSelectedIndex();
        Package paket;
        for (Map.Entry<String, Package> set : DeliveryList.entrySet()) {
//            if (set.getValue().getSender().equalsIgnoreCase(namaPengirim.getText()) && set.getValue().getFrom().equalsIgnoreCase(alamatPengirim.getText()) && set.getValue().getReceiver().equalsIgnoreCase(namaPenerima.getText()) && set.getValue().getDestination().equalsIgnoreCase(alamatPenerima.getText())) {
//                this.ARRPackageList.add(set.getValue());
//            }
            paket = set.getValue();
            if (set.getValue().getResi().equals(ARRPackageList.get(SelectedObj).getResi())) {
                set.getValue().getTrack().add("Barang dalam perjalanan");
                ARRPackageList.clear();
                listPaket.removeAll();
                generateElement();
                currentKurir.getDeliveredPackages().add(paket);
                JOptionPane.showMessageDialog(null, "Barang berhasil dipick-up", "DNF App", 1);
                break;
            }
        }

    }//GEN-LAST:event_pickupButtonActionPerformed

    private void btnKluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListPaketKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListPaketKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListPaketKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListPaketKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListPaketKurir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatPenerima;
    private javax.swing.JTextField alamatPengirim;
    private javax.swing.JLabel bgListPaket;
    private javax.swing.JButton btnKluar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listPaket;
    private javax.swing.JTextField namaPenerima;
    private javax.swing.JTextField namaPengirim;
    private javax.swing.JButton pickupButton;
    // End of variables declaration//GEN-END:variables
}
