/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dnfapp;

import java.util.HashMap;
import javax.swing.JFrame;
/**
 *
 * @author Frans
 */
public class LoginMenu extends javax.swing.JFrame {

    private HashMap<String , User> userlist = new HashMap<String, User>();
    
    /**
     * Creates new form LoginMenu
     */
    public LoginMenu() {
        initComponents();
    }
    
    public LoginMenu(HashMap<String, String> userlist){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserPassField = new javax.swing.JPasswordField();
        UsernameField = new javax.swing.JTextField();
        CreateAccButton = new javax.swing.JButton();
        SignInButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserPassField.setBackground(new java.awt.Color(255, 255, 255));
        UserPassField.setForeground(new java.awt.Color(0, 0, 0));
        UserPassField.setBorder(null);
        UserPassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPassFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UserPassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 530, 420, 30));

        UsernameField.setBackground(new java.awt.Color(255, 255, 255));
        UsernameField.setForeground(new java.awt.Color(0, 0, 0));
        UsernameField.setText("Username");
        UsernameField.setBorder(null);
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 440, 440, 30));

        CreateAccButton.setBackground(new java.awt.Color(30, 105, 255));
        CreateAccButton.setForeground(new java.awt.Color(30, 120, 152));
        CreateAccButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Create_Acc_Icon.png"))); // NOI18N
        CreateAccButton.setBorder(null);
        CreateAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CreateAccButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 710, 240, 70));

        SignInButton.setBackground(new java.awt.Color(30, 105, 255));
        SignInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Signin_icon.png"))); // NOI18N
        SignInButton.setBorder(null);
        SignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SignInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 700, 230, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Login.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1090));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccButtonActionPerformed
        int userAmount = userlist.size();
        if(userAmount==0){
            CreateAccountPage CAP = new CreateAccountPage();
            dispose();          //dispose of current JFrame. This is used to make performance better.
            CAP.setVisible(true);
            CAP.pack();
            CAP.setLocationRelativeTo(null);
            CAP.setDefaultCloseOperation(CreateAccountPage.EXIT_ON_CLOSE);
        }
        else{
            CreateAccountPage CAP = new CreateAccountPage(userlist);
            dispose();          //dispose of current JFrame. This is used to make performance better.
            CAP.setVisible(true);
            CAP.pack();
            CAP.setLocationRelativeTo(null);
            CAP.setDefaultCloseOperation(CreateAccountPage.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_CreateAccButtonActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void UserPassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserPassFieldActionPerformed

    private void SignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInButtonActionPerformed
        boolean Verify = true;
        String logUsername = UsernameField.getText();
        String logPass = String.valueOf(UserPassField.getPassword());
        if(userlist.containsKey(logUsername)){
            User designated = userlist.get(logUsername);
            String passCheck = designated.getPassword();
            if(!passCheck.equals(logPass)){
                Verify=false;
            }
        }
        else{
            Verify = false;
        }
        if(!Verify){
            
        }
        else{
            
        }
    }//GEN-LAST:event_SignInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccButton;
    private javax.swing.JButton SignInButton;
    private javax.swing.JPasswordField UserPassField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
