/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dnfapp;

import java.awt.Color;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Map;
import java.util.Random;

/**
 *
 * @author Felicia Pangestu
 */
public class RegisterKurir extends javax.swing.JFrame {

    /**
     * Creates new form RegisterKurir
     */
    
    private HashMap<String, User> userlist = new HashMap<String, User>();
    private HashMap<String, String> usedEmail = new HashMap<String, String>();
    private HashMap<String, Package> DeliveryList = new HashMap<String, Package>();
    private HashMap<String, Kurir> ListKurir = new HashMap<String, Kurir>();


    public RegisterKurir() {
        initComponents();
    }

    //main cons.
    public RegisterKurir(HashMap<String, User> userlist, HashMap<String, Package> DeliveryList, HashMap<String, Kurir> ListKurir, HashMap<String, String> usedEmail) {
        initComponents();
        this.userlist = userlist;
        this.DeliveryList = DeliveryList;
        this.ListKurir = ListKurir;
        this.usedEmail = usedEmail;
    }
    
    //static global char arr to generate random string
    private static char[] chars = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'q', 'w', 'e', 'r', 't', 'z', 'u', 'i', 'o', 'p', 'a', 's',
        'd', 'f', 'g', 'h', 'j', 'k', 'l', 'y', 'x', 'c', 'v', 'b', 'n', 'm', 'Q', 'W', 'E', 'R', 'T', 'Z', 'U', 'I', 'O', 'P', 'A',
        'S', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'Y', 'X', 'C', 'V', 'B', 'N', 'M' };

    //randomString generator procedure
    private static String randomString(int length) {
        StringBuilder stringBuilder = new StringBuilder();

        for (int i = 0; i < length; i++) {
            stringBuilder.append(chars[new Random().nextInt(chars.length)]);
        }
        return stringBuilder.toString();
    }
    
    //testing tool.
    public void GenerateTestObject(){

        System.out.println("Called Generator Method");
        for(int i = 0;i<100;i++){
            String randUsername = randomString(7);
            Kurir generatedKurir = new Kurir(randUsername,randomString(7),randomString(7));
            this.ListKurir.put(randUsername, generatedKurir);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NamaKurir = new javax.swing.JTextField();
        UsernameKurir = new javax.swing.JTextField();
        DaftarKurirButton = new javax.swing.JButton();
        cancelDaftarKurir = new javax.swing.JButton();
        PasswordKurir = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 726, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 726, -1, -1));

        NamaKurir.setBackground(new java.awt.Color(62, 97, 155));
        NamaKurir.setFont(new java.awt.Font("Dialog", 3, 16)); // NOI18N
        NamaKurir.setForeground(new java.awt.Color(255, 255, 255));
        NamaKurir.setBorder(null);
        NamaKurir.setCaretColor(new Color(255,255,255));
        NamaKurir.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        NamaKurir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NamaKurirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NamaKurirFocusLost(evt);
            }
        });
        NamaKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaKurirActionPerformed(evt);
            }
        });
        getContentPane().add(NamaKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 225, 492, 30));

        UsernameKurir.setBackground(new java.awt.Color(62, 97, 155));
        UsernameKurir.setFont(new java.awt.Font("Dialog", 3, 16)); // NOI18N
        UsernameKurir.setForeground(new java.awt.Color(255, 255, 255));
        UsernameKurir.setBorder(null);
        UsernameKurir.setCaretColor(new Color(255,255,255));
        UsernameKurir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameKurirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameKurirFocusLost(evt);
            }
        });
        UsernameKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameKurirActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 310, 445, 30));

        DaftarKurirButton.setBackground(new java.awt.Color(62, 97, 155));
        DaftarKurirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button_3.png"))); // NOI18N
        DaftarKurirButton.setBorder(null);
        DaftarKurirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarKurirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DaftarKurirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 260, 70));

        cancelDaftarKurir.setBackground(new java.awt.Color(62, 97, 155));
        cancelDaftarKurir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button_2.png"))); // NOI18N
        cancelDaftarKurir.setBorder(null);
        cancelDaftarKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelDaftarKurirActionPerformed(evt);
            }
        });
        getContentPane().add(cancelDaftarKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 490, 200, 60));

        PasswordKurir.setBackground(new java.awt.Color(62, 97, 155));
        PasswordKurir.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        PasswordKurir.setBorder(null);
        PasswordKurir.setCaretColor(new Color(255,255,255));
        PasswordKurir.setForeground(new Color(255,255,255));
        PasswordKurir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordKurirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordKurirFocusLost(evt);
            }
        });
        PasswordKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordKurirActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordKurir, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 395, 445, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Regis_kurir.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DaftarKurirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarKurirButtonActionPerformed
        String namaKurir = NamaKurir.getText();
        String unameKurir = UsernameKurir.getText();
        String passwordKurir = String.valueOf(PasswordKurir.getPassword());
        boolean jadiKurir = false;
        if (namaKurir.equals("Nama Kurir")) {
            JOptionPane.showMessageDialog(null, "Nama Kurir diisi terlebih dahulu!");
        } 
        else {
            if (unameKurir.equals("Username Kurir")||unameKurir.equals("")) {
                JOptionPane.showMessageDialog(null, "Username Kurir diisi terlebih dahulu!");
            }
            //method Test JList.
            else if(unameKurir.equalsIgnoreCase("TESTFILL")||namaKurir.equalsIgnoreCase("TESTFILL")){
                GenerateTestObject();
                AdminMenu AM = new AdminMenu(userlist, DeliveryList, ListKurir, usedEmail);
                dispose();
                AM.setVisible(true);
                AM.pack();
                AM.setLocationRelativeTo(null);
                AM.setDefaultCloseOperation(LoginMenu.EXIT_ON_CLOSE);
                JOptionPane.showMessageDialog(null, "Generated 100 Test Object of Class Kurir!", "DNF App", 1);
            }
            else {
                if (passwordKurir.equals("Password Kurir")||passwordKurir.equals("")) {
                    JOptionPane.showMessageDialog(null, "Password Kurir diisi terlebih dahulu!");
                } 
                else {
                    if (ListKurir.containsKey(unameKurir)) {
                        jadiKurir = true;
                    }
                    
                    if(!jadiKurir){
                        Kurir newKurir = new Kurir(unameKurir, namaKurir, passwordKurir);
                        ListKurir.put(unameKurir, newKurir);
                        AdminMenu AM = new AdminMenu(userlist, DeliveryList, ListKurir, usedEmail);
                        dispose();
                        AM.setVisible(true);
                        AM.pack();
                        AM.setLocationRelativeTo(null);
                        AM.setDefaultCloseOperation(LoginMenu.EXIT_ON_CLOSE);
                        JOptionPane.showMessageDialog(null, "Berhasil mendafatarkan " + namaKurir + " !", "DNF App", 1);
                    } else{
                        JOptionPane.showMessageDialog(null, "Kurir sudah terdaftar!", "DNF App", 2);   
                    }
                }
            }
        }
        
    }//GEN-LAST:event_DaftarKurirButtonActionPerformed

    private void NamaKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaKurirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaKurirActionPerformed

    private void NamaKurirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NamaKurirFocusGained
        if (NamaKurir.getText().equals("Nama Kurir")) {
            NamaKurir.setText("");
            NamaKurir.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_NamaKurirFocusGained

    private void NamaKurirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NamaKurirFocusLost
        if (NamaKurir.getText().equals("")) {
            NamaKurir.setText("Nama Kurir");
            NamaKurir.setForeground(new Color(255, 255, 255));
        }
        
    }//GEN-LAST:event_NamaKurirFocusLost

    private void PasswordKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordKurirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordKurirActionPerformed

    private void PasswordKurirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordKurirFocusLost
        String password = String.valueOf(PasswordKurir.getPassword());
        //
        if (password.toLowerCase().equals("password") || password.toLowerCase().equals("")) {
            PasswordKurir.setText("Password");
            PasswordKurir.setEchoChar((char) 0);
            PasswordKurir.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_PasswordKurirFocusLost

    private void PasswordKurirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordKurirFocusGained
        PasswordKurir.setEchoChar('*');
        String password = String.valueOf(PasswordKurir.getPassword());

        if (password.toLowerCase().equals("password")) {
            PasswordKurir.setText("");
            PasswordKurir.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_PasswordKurirFocusGained

    private void UsernameKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameKurirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameKurirActionPerformed

    private void UsernameKurirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameKurirFocusLost
        if (UsernameKurir.getText().equals("")) {
            UsernameKurir.setText("Username Kurir");
            UsernameKurir.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_UsernameKurirFocusLost

    private void UsernameKurirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameKurirFocusGained
        if (UsernameKurir.getText().equals("Username Kurir")) {
            UsernameKurir.setText("");
            UsernameKurir.setForeground(new Color(255, 255, 255));
        }
    }//GEN-LAST:event_UsernameKurirFocusGained

    private void cancelDaftarKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelDaftarKurirActionPerformed
        AdminMenu AM = new AdminMenu(userlist, DeliveryList, ListKurir, usedEmail);
        dispose();
        AM.setVisible(true);
        AM.pack();
        AM.setLocationRelativeTo(null);
        AM.setDefaultCloseOperation(LoginMenu.EXIT_ON_CLOSE);
    }//GEN-LAST:event_cancelDaftarKurirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterKurir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DaftarKurirButton;
    private javax.swing.JTextField NamaKurir;
    private javax.swing.JPasswordField PasswordKurir;
    private javax.swing.JTextField UsernameKurir;
    private javax.swing.JButton cancelDaftarKurir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
