/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dnfapp;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Frans
 */
public class UserMainMenu extends javax.swing.JFrame implements GenerateCity,CityCalc{
    //boolean state
    private boolean cek_resi;
    private boolean home_menu;
    private boolean setting;
    private boolean history;
    private boolean send;
    //current user obj
    private User currentUser;
    //HashMaps to Pass.
    private HashMap<String, User> userlist = new HashMap<String, User>();
    private HashMap<String, String> usedEmail = new HashMap<String, String>();
    private HashMap<String, Package> DeliveryList = new HashMap<String, Package>();
    private HashMap<String, Kurir> ListKurir = new HashMap<String, Kurir>();
    
    //private Generated HashMaps&ArrayList for City Index
    private HashMap<String, Kota> MapKota = new HashMap<String, Kota>();
    private ArrayList<String> listkota = new ArrayList<>();
    
    public UserMainMenu() {
        initComponents();
        generateCityCalc();
    }
    
    public UserMainMenu(HashMap<String, User> userlist, HashMap<String, String> usedEmail){
        initComponents();
        this.userlist=userlist;
        this.usedEmail=usedEmail;
        generateCityCalc();
    }
    
    public UserMainMenu(HashMap<String, User> userlist,HashMap<String, String> usedEmail, HashMap<String, Package> DeliveryList,  HashMap<String, Kurir> ListKurir, User currentUser){
        initComponents();
        this.userlist=userlist;
        this.usedEmail=usedEmail;
        this.DeliveryList=DeliveryList;
        this.ListKurir=ListKurir;
        this.currentUser=currentUser;
        this.setResizable(false);
        UserMenuBG.requestFocus();
        WelcomeLabel.setText("Welcome, "+currentUser.getUsername());
        this.cek_resi=false;
        this.home_menu=true;
        this.setting=false;
        this.history=false;
        this.send=false;
        ButtonController(false,true,false,false,false);
        generateCityCalc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Profile = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        WelcomeLabel = new javax.swing.JLabel();
        SendBeratField = new javax.swing.JTextField();
        AsalField = new javax.swing.JTextField();
        CekResiButton = new javax.swing.JButton();
        SettingButton = new javax.swing.JButton();
        CalculateBtn = new javax.swing.JButton();
        PriceLabel = new javax.swing.JLabel();
        TujuanField = new javax.swing.JTextField();
        TujuanCombobox = new javax.swing.JComboBox<>();
        AsalCombobox = new javax.swing.JComboBox<>();
        SendPackageBG = new javax.swing.JLabel();
        SearchButton = new javax.swing.JButton();
        Vector = new javax.swing.JLabel();
        CekHistoryButton = new javax.swing.JButton();
        SendPackageButton = new javax.swing.JButton();
        SearchBar = new javax.swing.JTextField();
        SearchBarBG = new javax.swing.JLabel();
        UserMenuBG = new javax.swing.JLabel();
        SeeDetailButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HistoryList = new javax.swing.JList<>();
        BGHistory = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Profile.png"))); // NOI18N
        getContentPane().add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 90, -1, -1));

        LogOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Logout.png"))); // NOI18N
        LogOutButton.setBorderPainted(false);
        LogOutButton.setContentAreaFilled(false);
        LogOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutButtonMouseClicked(evt);
            }
        });
        getContentPane().add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 595, 70, 70));

        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Home_1.png"))); // NOI18N
        HomeButton.setBorderPainted(false);
        HomeButton.setContentAreaFilled(false);
        HomeButton.setPreferredSize(new java.awt.Dimension(144, 39));
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 186, 53));

        WelcomeLabel.setFont(new java.awt.Font("Fira Sans", 3, 18)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(WelcomeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 180, 215, 40));
        getContentPane().add(SendBeratField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 280, 40));
        getContentPane().add(AsalField, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 250, 40));

        CekResiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_CekResi_0.png"))); // NOI18N
        CekResiButton.setBorderPainted(false);
        CekResiButton.setContentAreaFilled(false);
        CekResiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CekResiButtonMouseClicked(evt);
            }
        });
        CekResiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekResiButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CekResiButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 186, 53));

        SettingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Setting_0.png"))); // NOI18N
        SettingButton.setBorderPainted(false);
        SettingButton.setContentAreaFilled(false);
        SettingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SettingButtonMouseClicked(evt);
            }
        });
        getContentPane().add(SettingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 370, 186, 53));

        CalculateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Hitung.png"))); // NOI18N
        CalculateBtn.setBorderPainted(false);
        CalculateBtn.setContentAreaFilled(false);
        CalculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CalculateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 135, 35));

        PriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(PriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 390, 120));
        getContentPane().add(TujuanField, new org.netbeans.lib.awtextra.AbsoluteConstraints(875, 240, 240, 40));

        TujuanCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Kota-" }));
        TujuanCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuanComboboxActionPerformed(evt);
            }
        });
        getContentPane().add(TujuanCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1115, 240, 90, 40));

        AsalCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Kota-" }));
        getContentPane().add(AsalCombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 100, 40));

        SendPackageBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_BG_SendPackage.png"))); // NOI18N
        getContentPane().add(SendPackageBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Search.png"))); // NOI18N
        SearchButton.setBorderPainted(false);
        SearchButton.setContentAreaFilled(false);
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 329, 111, 49));
        SearchButton.setVisible(false);

        Vector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Vector.gif"))); // NOI18N
        getContentPane().add(Vector, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, -1, -1));

        CekHistoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_ShippingHistory.png"))); // NOI18N
        CekHistoryButton.setBorderPainted(false);
        CekHistoryButton.setContentAreaFilled(false);
        CekHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CekHistoryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CekHistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 380, 150));

        SendPackageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_SendPackage.png"))); // NOI18N
        SendPackageButton.setBorderPainted(false);
        SendPackageButton.setContentAreaFilled(false);
        SendPackageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendPackageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SendPackageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 380, 150));

        SearchBar.setFont(new java.awt.Font("Fira Sans", 1, 20)); // NOI18N
        SearchBar.setToolTipText("");
        SearchBar.setBorder(null);
        SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBarActionPerformed(evt);
            }
        });
        getContentPane().add(SearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 324, 430, 57));

        SearchBarBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_TextField_Search.png"))); // NOI18N
        getContentPane().add(SearchBarBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));
        SearchBarBG.setVisible(false);

        UserMenuBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_BG_Home.png"))); // NOI18N
        getContentPane().add(UserMenuBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        SeeDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_LihatDetail.png"))); // NOI18N
        SeeDetailButton.setBorderPainted(false);
        SeeDetailButton.setContentAreaFilled(false);
        getContentPane().add(SeeDetailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 640, 154, 78));

        jScrollPane1.setViewportView(HistoryList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 440, 380));

        BGHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_BG_ShippingHistory.png"))); // NOI18N
        getContentPane().add(BGHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CekResiButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CekResiButtonMouseClicked
        if(!cek_resi){
            ButtonController(false,false,true,false,false);
        }
    }//GEN-LAST:event_CekResiButtonMouseClicked

    private void HomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseClicked
        if(!home_menu){
            ButtonController(false,true,false,false,false);
        }
    }//GEN-LAST:event_HomeButtonMouseClicked

    private void SettingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SettingButtonMouseClicked
        if(!setting){
            ButtonController(true,false,false,false,false);
        }
    }//GEN-LAST:event_SettingButtonMouseClicked

    private void LogOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutButtonMouseClicked
        LoginMenu LM = new LoginMenu(userlist, usedEmail, DeliveryList, ListKurir);
        dispose();
        LM.setVisible(true);
        LM.pack();
        LM.setLocationRelativeTo(null);
        LM.setDefaultCloseOperation(CreateAccountPage.EXIT_ON_CLOSE);
        LM.setResizable(false);
    }//GEN-LAST:event_LogOutButtonMouseClicked

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        String RESI = this.SearchBar.getText();
        if(RESI.equals("")){
            JOptionPane.showMessageDialog(null, "Tolong masukkan resi yang ingin dicari terlebih dahulu", "Invalid Input!",JOptionPane.WARNING_MESSAGE);
        }
        else{
            if (DeliveryList.containsKey(RESI)){
                Package selected = DeliveryList.get(RESI);
                DetailPackage DP = new DetailPackage(userlist,usedEmail,DeliveryList,ListKurir, selected,currentUser);
                dispose();
                DP.setVisible(true);
                DP.pack();
                DP.setLocationRelativeTo(null);
                DP.setDefaultCloseOperation(DetailPackage.EXIT_ON_CLOSE);
                DP.setResizable(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "Resi tidak ditemukan!", "Resi Invalid!",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void CekHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekHistoryButtonActionPerformed
        UpdateState(false,false,false,true,false);
        ButtonController(false,false,false,true,false);
    }//GEN-LAST:event_CekHistoryButtonActionPerformed

    private void CekResiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CekResiButtonActionPerformed

    }//GEN-LAST:event_CekResiButtonActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    private void SendPackageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendPackageButtonActionPerformed
        if(!send){
            ButtonController(false,false,false,false,true);
        }
    }//GEN-LAST:event_SendPackageButtonActionPerformed

    private void CalculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateBtnActionPerformed
        
    }//GEN-LAST:event_CalculateBtnActionPerformed

    private void TujuanComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuanComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TujuanComboboxActionPerformed

    public void generateCityCalc(){
        MapKota = GenerateCity.generateCityMap(MapKota);
        listkota = GenerateCity.generateCity(listkota);
        for(int i =0;i<listkota.size();i++){
            AsalCombobox.addItem(listkota.get(i));
            TujuanCombobox.addItem(listkota.get(i));
        }
    }
    
    private void UpdateState(boolean setting, boolean home, boolean cek, boolean history, boolean send){
        this.cek_resi=cek;
        this.home_menu=home;
        this.setting=setting;
        this.history=history;
        this.send=send;
    }
    
    private void UpdateVisibility(int x){
        if(x==1){ // Home Mode
            this.UserMenuBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_BG_Home.png")));
            this.SearchBarBG.setVisible(false);
            this.SearchButton.setVisible(false);
            this.Vector.setVisible(true);
            this.SearchBar.setVisible(false);
            this.SearchBar.setEditable(false);
            this.SearchButton.setEnabled(false);
            this.CekHistoryButton.setVisible(true);
            this.CekHistoryButton.setEnabled(true);
            this.SendPackageButton.setVisible(true);
            this.SendPackageButton.setEnabled(true);
            this.HistoryList.setEnabled(false);
            this.HistoryList.setVisible(false);
            this.UserMenuBG.setVisible(true);
            this.AsalField.setVisible(false);
            this.AsalField.setEditable(false);
            this.TujuanField.setVisible(false);
            this.TujuanField.setEditable(false);
            this.TujuanCombobox.setVisible(false);
            this.TujuanCombobox.setEditable(false);
            this.SendPackageBG.setVisible(false);
            this.SendBeratField.setVisible(false);
            this.SendBeratField.setEditable(false);
            this.PriceLabel.setVisible(false);
            this.CalculateBtn.setVisible(false);
            this.CalculateBtn.setEnabled(false);
            this.AsalCombobox.setVisible(false);
            this.AsalCombobox.setEditable(false);
            this.SeeDetailButton.setVisible(false);
            this.SeeDetailButton.setEnabled(false);
        }
        else if(x==2){ //Cek Resi Mode
            this.UserMenuBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_BG_CekResi.png")));
            this.SearchBarBG.setVisible(true);
            this.SearchButton.setVisible(true);
            this.Vector.setVisible(false);
            this.SearchBar.setVisible(true);
            this.SearchBar.setEditable(true);
            this.SearchButton.setEnabled(true);
            this.CekHistoryButton.setVisible(false);
            this.CekHistoryButton.setEnabled(false);
            this.SendPackageButton.setVisible(false);
            this.SendPackageButton.setEnabled(false);
            this.HistoryList.setEnabled(false);
            this.HistoryList.setVisible(false);
            this.UserMenuBG.setVisible(true);
            this.AsalField.setVisible(false);
            this.AsalField.setEditable(false);
            this.TujuanField.setVisible(false);
            this.TujuanField.setEditable(false);
            this.TujuanCombobox.setVisible(false);
            this.TujuanCombobox.setEditable(false);
            this.SendPackageBG.setVisible(false);
            this.SendBeratField.setVisible(false);
            this.SendBeratField.setEditable(false);
            this.PriceLabel.setVisible(false);
            this.CalculateBtn.setVisible(false);
            this.CalculateBtn.setEnabled(false);
            this.AsalCombobox.setVisible(false);
            this.AsalCombobox.setEditable(false);
            this.SeeDetailButton.setVisible(false);
            this.SeeDetailButton.setEnabled(false);
        }
        else if(x==3){ //Settings Mode
            this.SearchBarBG.setVisible(false);
            this.SearchButton.setVisible(false);
            this.Vector.setVisible(false);
            this.SearchBar.setVisible(false);
            this.SearchBar.setEditable(false);
            this.SearchButton.setEnabled(false);
            this.CekHistoryButton.setVisible(false);
            this.CekHistoryButton.setEnabled(false);
            this.SendPackageButton.setVisible(false);
            this.SendPackageButton.setEnabled(false);
            this.HistoryList.setEnabled(false);
            this.HistoryList.setVisible(false);
            this.UserMenuBG.setVisible(true);
            this.AsalField.setVisible(false);
            this.AsalField.setEditable(false);
            this.TujuanField.setVisible(false);
            this.TujuanField.setEditable(false);
            this.TujuanCombobox.setVisible(false);
            this.TujuanCombobox.setEditable(false);
            this.SendPackageBG.setVisible(false);
            this.SendBeratField.setVisible(false);
            this.SendBeratField.setEditable(false);
            this.PriceLabel.setVisible(false);
            this.CalculateBtn.setVisible(false);
            this.CalculateBtn.setEnabled(false);
            this.AsalCombobox.setVisible(false);
            this.AsalCombobox.setEditable(false);
            this.SeeDetailButton.setVisible(false);
            this.SeeDetailButton.setEnabled(false);
        }
        else if(x==4){ //See History Mode
            this.SearchBarBG.setVisible(false);
            this.SearchButton.setVisible(false);
            this.Vector.setVisible(false);
            this.SearchBar.setVisible(false);
            this.SearchBar.setEditable(false);
            this.SearchButton.setEnabled(false);
            this.CekHistoryButton.setVisible(false);
            this.CekHistoryButton.setEnabled(false);
            this.SendPackageButton.setVisible(false);
            this.SendPackageButton.setEnabled(false);
            this.HistoryList.setEnabled(false);
            this.HistoryList.setVisible(false);
            this.UserMenuBG.setVisible(false);
            this.BGHistory.setVisible(true);
            this.AsalField.setVisible(false);
            this.AsalField.setEditable(false);
            this.TujuanField.setVisible(false);
            this.TujuanField.setEditable(false);
            this.TujuanCombobox.setVisible(false);
            this.TujuanCombobox.setEditable(false);
            this.SendPackageBG.setVisible(false);
            this.SendBeratField.setVisible(false);
            this.SendBeratField.setEditable(false);
            this.PriceLabel.setVisible(false);
            this.CalculateBtn.setVisible(false);
            this.CalculateBtn.setEnabled(false);
            this.AsalCombobox.setVisible(false);
            this.AsalCombobox.setEditable(false);
            this.SeeDetailButton.setVisible(false);
            this.SeeDetailButton.setEnabled(false);
            this.SeeDetailButton.setVisible(true);
            this.SeeDetailButton.setEnabled(true);
        }
        else if(x==5){ //Send Package Mode
            this.SearchBarBG.setVisible(false);
            this.SearchButton.setVisible(false);
            this.Vector.setVisible(false);
            this.SearchBar.setVisible(false);
            this.SearchBar.setEditable(false);
            this.SearchButton.setEnabled(false);
            this.CekHistoryButton.setVisible(false);
            this.CekHistoryButton.setEnabled(false);
            this.SendPackageButton.setVisible(false);
            this.SendPackageButton.setEnabled(false);
            this.HistoryList.setEnabled(false);
            this.HistoryList.setVisible(false);
            this.UserMenuBG.setVisible(false);
            this.BGHistory.setVisible(false);
            this.AsalField.setVisible(true);
            this.AsalField.setEditable(true);
            this.TujuanField.setVisible(true);
            this.TujuanField.setEditable(true);
            this.TujuanCombobox.setVisible(true);
            this.TujuanCombobox.setEditable(true);
            this.SendPackageBG.setVisible(true);
            this.SendBeratField.setVisible(true);
            this.SendBeratField.setEditable(true);
            this.PriceLabel.setVisible(true);
            this.CalculateBtn.setVisible(true);
            this.CalculateBtn.setEnabled(true);
            this.AsalCombobox.setVisible(true);
            this.AsalCombobox.setEditable(true);
            this.SeeDetailButton.setVisible(true);
            this.SeeDetailButton.setEnabled(true);
            this.SeeDetailButton.setVisible(false);
            this.SeeDetailButton.setEnabled(false);
        }
    }
    
    private void ButtonController(boolean setting, boolean home, boolean cek,boolean history, boolean send){
        if(setting&&!home&&!cek&&!history&&!send){ //Settings Mode
            UpdateState(setting,home,cek,false,false);
            this.SettingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Setting_1.png")));
            this.HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Home_0.png")));
            this.CekResiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_CekResi_0.png")));
            UpdateVisibility(3);
        }
        else if(!setting&&home&&!cek&&!history&&!send){ //Home MOde
            UpdateState(setting,home,cek,false,false);
            this.SettingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Setting_0.png")));
            this.HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Home_1.png")));
            this.CekResiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_CekResi_0.png")));
            UpdateVisibility(1);
        }
        else if(!setting&&!home&&cek&&!history&&!send){ //Cek Resi Mode
            UpdateState(setting,home,cek,false,false);
            this.SettingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Setting_0.png")));
            this.HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Home_0.png")));
            this.CekResiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_CekResi_1.png")));
            UpdateVisibility(2);
        }
        else if(!setting&&!home&&!cek&&history&&!send){ //See History Mode
            UpdateState(setting,home,cek,history,send);
            this.SettingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Setting_0.png")));
            this.HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Home_0.png")));
            this.CekResiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_CekResi_0.png")));
            UpdateVisibility(4);
        }
        else if(!setting&&!home&&!cek&&!history&&send){ //Send Package Mode
            UpdateState(setting,home,cek,history,send);
            this.SettingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Setting_0.png")));
            this.HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_Home_0.png")));
            this.CekResiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User_Button_CekResi_0.png")));
            UpdateVisibility(5);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AsalCombobox;
    private javax.swing.JTextField AsalField;
    private javax.swing.JLabel BGHistory;
    private javax.swing.JButton CalculateBtn;
    private javax.swing.JButton CekHistoryButton;
    private javax.swing.JButton CekResiButton;
    private javax.swing.JList<String> HistoryList;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel Profile;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JLabel SearchBarBG;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton SeeDetailButton;
    private javax.swing.JTextField SendBeratField;
    private javax.swing.JLabel SendPackageBG;
    private javax.swing.JButton SendPackageButton;
    private javax.swing.JButton SettingButton;
    private javax.swing.JComboBox<String> TujuanCombobox;
    private javax.swing.JTextField TujuanField;
    private javax.swing.JLabel UserMenuBG;
    private javax.swing.JLabel Vector;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
